### ISSUE TITLE
data_reprocess.py

### ISSUE THREAD

**Issue by LINK3599** [simoncos/lola#3]
C:\Users\User\Desktop\lola-master>python3 data_preprocess.py
Traceback (most recent call last):
  File "data_preprocess.py", line 3, in <module>
    from statics import champions
ImportError: No module named 'statics'

Where can i get this module ? Thanks

**Comment by simoncos** [comment]
Same issue as https://github.com/simoncos/lola/issues/2
Will fix it this week hopefully:)
