### ISSUE TITLE
data_crawl.py

### ISSUE THREAD

**Issue by LINK3599** [simoncos/lola#4]
When I running this code, the below error sometime occurs.

160 matches in 548 processed.
170 matches in 548 processed.
180 matches in 548 processed.
Traceback (most recent call last):
  File "data_crawl.py", line 357, in <module>
    main()
  File "data_crawl.py", line 51, in main
    begin_crawling(api_key='d70740d1-9d4b-4f1a-8f12-e34bbc5c5179', seed_summoner_id='20570900')
  File "data_crawl.py", line 114, in begin_crawling
    match_to_sqlite(match, summoner, conn)
  File "data_crawl.py", line 181, in match_to_sqlite
    if match.timeline.frames is not None:
AttributeError: 'NoneType' object has no attribute 'frames'

**Comment by simoncos** [comment]
What season, ranked_queue did you use?

**Comment by LINK3599** [comment]
SEASON2016, TEAM_BUILDER_DRAFT_RANKED_5x5

**Comment by LINK3599** [comment]
Again, I changed the season and queue back, the error still occured.

Summoner 24763111 in RANKED_SOLO_5x5, PRESEASON2016:
Total Match Number of the summoner: 172
10 matches in 172 processed.
20 matches in 172 processed.
30 matches in 172 processed.
Got a 400 or 404
Traceback (most recent call last):
  File "data_crawl.py", line 366, in <module>
    main()
  File "data_crawl.py", line 62, in main
    begin_crawling(seed_summoner_id='19766583', seasons='PRESEASON2016',ranked_queues='RANKED_SOLO_5x5')
  File "data_crawl.py", line 123, in begin_crawling
    match_to_sqlite(match, summoner, conn)
  File "data_crawl.py", line 190, in match_to_sqlite
    if match.timeline.frames is not None:
AttributeError: 'NoneType' object has no attribute 'frames'

**Comment by simoncos** [comment]
I believe this error means that `match.timeline` of the match you were trying to process is `None`. We didn't come across this kind of situation before. So I suggest you to print the `match_id` of the match in the `match_to_sqlite()` function, so that we can check it with Riot API.

Besides, did you change the region?

**Comment by LINK3599** [comment]
Yes, I set the region as "EUW"

**Comment by simoncos** [comment]
Try the latest data_crawl.py: https://github.com/simoncos/lola/commit/7223bf35cfdaa81eadfb1ef6a3c9bdce4bf0db28
